apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: 3-18-app
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhn-support-csears/3-18-app:8fff79e3cee257c2492993e878acd4aea2608211@sha256:3a78dc282ebc72b856ca1880f3fae223a9fafec78711c564fd3984c06bd03921
        name: container-image  
