apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: 3-18-app
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhn-support-csears/3-18-app:25cb4182f98b25eb65638f0edd597021e4f8106a@sha256:ecafdd12fcabfca2045b34bbc3f5d4c556f210cf2129045be95bb941b202314b
        name: container-image  
